name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
          run_install: |
            - args: [--frozen-lockfile]

      - name: Build
        run: |
          pnpm build

      - name: Test
        run: |
          pnpm test
